version: '3.8'

volumes:
    postgres_data:
    redisinsight:


networks:
    gsbank-network:
    redis:
        driver: bridge
    postgres_network:
        driver: bridge

services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        networks:
            - postgres_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./scripts/docker/postgres:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "postgres",
                    "-U",
                    "postgres"
                ]
            timeout: 45s
            interval: 10s
            retries: 10
    redis:
        restart: always
        image: redis:alpine
        networks:
            - redis
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    redisinsight:
        image: redislabs/redisinsight:latest
        networks:
            - redis
        ports:
            - 8001:8001
        volumes:
            - redisinsight:/db
