import { ListActionResponse } from 'adminjs';

export const joinSoftDeleteParams = (): ListActionResponse => {
  return {
    meta: {
      total: 2,
      perPage: 10,
      page: 1,
      direction: 'asc',
      sortBy: 'productId',
    },
    records: [
      {
        params: {
          id: 3,
          description: 'Plano com produto não excluído',
          summary: 'Plano com produto não excluído',
          productId: 1,
          prizeValue: 19,
          createdAt: '2022-05-06T15:17:28.957Z',
          updatedAt: '2022-05-06T15:17:28.957Z',
          deletedAt: null,
        },
        populated: {
          productId: {
            params: {
              id: 1,
              description: 'Produto não excluído',
              icon: 'uploads/products/1/cc53ad8a-c316-432d-a717-7069d13679d7.png',
              branchGroupNumber: 95,
              branchNumber: 95,
              createdAt: '2022-05-05T22:23:34.147Z',
              updatedAt: '2022-05-05T22:38:13.496Z',
              deletedAt: null,
            },
            populated: {},
            errors: {},
            id: '1',
            title: 'Produto não excluído',
            recordActions: [
              {
                name: 'show',
                actionType: 'record',
                icon: 'Screen',
                label: 'Show',
                resourceId: 'ProductEntity',
                guard: '',
                showFilter: false,
                component: undefined,
                showInDrawer: false,
                hideActionHeader: false,
                containerWidth: 1,
                layout: null,
                variant: 'default',
                parent: null,
                hasHandler: true,
                custom: {},
              },
              {
                name: 'edit',
                actionType: 'record',
                icon: 'Edit',
                label: 'Edit',
                resourceId: 'ProductEntity',
                guard: '',
                showFilter: false,
                component: undefined,
                showInDrawer: false,
                hideActionHeader: false,
                containerWidth: 1,
                layout: null,
                variant: 'default',
                parent: null,
                hasHandler: true,
                custom: {},
              },
              {
                name: 'delete',
                actionType: 'record',
                icon: 'TrashCan',
                label: 'Delete',
                resourceId: 'ProductEntity',
                guard: 'Do you really want to remove this item?',
                showFilter: false,
                component: false,
                showInDrawer: false,
                hideActionHeader: false,
                containerWidth: 1,
                layout: null,
                variant: 'danger',
                parent: null,
                hasHandler: true,
                custom: {},
              },
            ],
            bulkActions: [
              {
                name: 'bulkDelete',
                actionType: 'bulk',
                icon: 'Delete',
                label: 'Delete all',
                resourceId: 'ProductEntity',
                guard: '',
                showFilter: false,
                component: undefined,
                showInDrawer: true,
                hideActionHeader: false,
                containerWidth: '500px',
                layout: null,
                variant: 'danger',
                parent: null,
                hasHandler: true,
                custom: {},
              },
            ],
          },
        },
        errors: {},
        id: '3',
        title: 'Plano com produto não excluído',
        recordActions: [
          {
            name: 'show',
            actionType: 'record',
            icon: 'Screen',
            label: 'Show',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'default',
            parent: null,
            hasHandler: true,
            custom: {},
          },
          {
            name: 'edit',
            actionType: 'record',
            icon: 'Edit',
            label: 'Edit',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'default',
            parent: null,
            hasHandler: true,
            custom: {},
          },
          {
            name: 'delete',
            actionType: 'record',
            icon: 'TrashCan',
            label: 'Delete',
            resourceId: 'PlanEntity',
            guard: 'Do you really want to remove this item?',
            showFilter: false,
            component: false,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'danger',
            parent: null,
            hasHandler: true,
            custom: {},
          },
        ],
        bulkActions: [
          {
            name: 'bulkDelete',
            actionType: 'bulk',
            icon: 'Delete',
            label: 'Delete all',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: true,
            hideActionHeader: false,
            containerWidth: '500px',
            layout: null,
            variant: 'danger',
            parent: null,
            hasHandler: true,
            custom: {},
          },
        ],
      },
      {
        params: {
          id: 9,
          description: 'Plano com produto excluído',
          summary: 'Plano com produto excluído',
          productId: 2,
          prizeValue: 77,
          createdAt: '2022-05-06T16:20:18.193Z',
          updatedAt: '2022-05-06T16:20:18.193Z',
          deletedAt: null,
        },
        populated: {},
        errors: {},
        id: '9',
        title: 'Plano com produto excluído',
        recordActions: [
          {
            name: 'show',
            actionType: 'record',
            icon: 'Screen',
            label: 'Show',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'default',
            parent: null,
            hasHandler: true,
            custom: {},
          },
          {
            name: 'edit',
            actionType: 'record',
            icon: 'Edit',
            label: 'Edit',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'default',
            parent: null,
            hasHandler: true,
            custom: {},
          },
          {
            name: 'delete',
            actionType: 'record',
            icon: 'TrashCan',
            label: 'Delete',
            resourceId: 'PlanEntity',
            guard: 'Do you really want to remove this item?',
            showFilter: false,
            component: false,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'danger',
            parent: null,
            hasHandler: true,
            custom: {},
          },
        ],
        bulkActions: [
          {
            name: 'bulkDelete',
            actionType: 'bulk',
            icon: 'Delete',
            label: 'Delete all',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: true,
            hideActionHeader: false,
            containerWidth: '500px',
            layout: null,
            variant: 'danger',
            parent: null,
            hasHandler: true,
            custom: {},
          },
        ],
      },
    ],
  };
};

export const joinSoftDeleteResponse = (): ListActionResponse => {
  return {
    meta: {
      total: 2,
      perPage: 10,
      page: 1,
      direction: 'asc',
      sortBy: 'productId',
    },
    records: [
      {
        params: {
          id: 3,
          description: 'Plano com produto não excluído',
          summary: 'Plano com produto não excluído',
          productId: 1,
          prizeValue: 19,
          createdAt: '2022-05-06T15:17:28.957Z',
          updatedAt: '2022-05-06T15:17:28.957Z',
          deletedAt: null,
        },
        populated: {
          productId: {
            params: {
              id: 1,
              description: 'Produto não excluído',
              icon: 'uploads/products/1/cc53ad8a-c316-432d-a717-7069d13679d7.png',
              branchGroupNumber: 95,
              branchNumber: 95,
              createdAt: '2022-05-05T22:23:34.147Z',
              updatedAt: '2022-05-05T22:38:13.496Z',
              deletedAt: null,
            },
            populated: {},
            errors: {},
            id: '1',
            title: 'Produto não excluído',
            recordActions: [
              {
                name: 'show',
                actionType: 'record',
                icon: 'Screen',
                label: 'Show',
                resourceId: 'ProductEntity',
                guard: '',
                showFilter: false,
                component: undefined,
                showInDrawer: false,
                hideActionHeader: false,
                containerWidth: 1,
                layout: null,
                variant: 'default',
                parent: null,
                hasHandler: true,
                custom: {},
              },
              {
                name: 'edit',
                actionType: 'record',
                icon: 'Edit',
                label: 'Edit',
                resourceId: 'ProductEntity',
                guard: '',
                showFilter: false,
                component: undefined,
                showInDrawer: false,
                hideActionHeader: false,
                containerWidth: 1,
                layout: null,
                variant: 'default',
                parent: null,
                hasHandler: true,
                custom: {},
              },
              {
                name: 'delete',
                actionType: 'record',
                icon: 'TrashCan',
                label: 'Delete',
                resourceId: 'ProductEntity',
                guard: 'Do you really want to remove this item?',
                showFilter: false,
                component: false,
                showInDrawer: false,
                hideActionHeader: false,
                containerWidth: 1,
                layout: null,
                variant: 'danger',
                parent: null,
                hasHandler: true,
                custom: {},
              },
            ],
            bulkActions: [
              {
                name: 'bulkDelete',
                actionType: 'bulk',
                icon: 'Delete',
                label: 'Delete all',
                resourceId: 'ProductEntity',
                guard: '',
                showFilter: false,
                component: undefined,
                showInDrawer: true,
                hideActionHeader: false,
                containerWidth: '500px',
                layout: null,
                variant: 'danger',
                parent: null,
                hasHandler: true,
                custom: {},
              },
            ],
          },
        },
        errors: {},
        id: '3',
        title: 'Plano com produto não excluído',
        recordActions: [
          {
            name: 'show',
            actionType: 'record',
            icon: 'Screen',
            label: 'Show',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'default',
            parent: null,
            hasHandler: true,
            custom: {},
          },
          {
            name: 'edit',
            actionType: 'record',
            icon: 'Edit',
            label: 'Edit',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'default',
            parent: null,
            hasHandler: true,
            custom: {},
          },
          {
            name: 'delete',
            actionType: 'record',
            icon: 'TrashCan',
            label: 'Delete',
            resourceId: 'PlanEntity',
            guard: 'Do you really want to remove this item?',
            showFilter: false,
            component: false,
            showInDrawer: false,
            hideActionHeader: false,
            containerWidth: 1,
            layout: null,
            variant: 'danger',
            parent: null,
            hasHandler: true,
            custom: {},
          },
        ],
        bulkActions: [
          {
            name: 'bulkDelete',
            actionType: 'bulk',
            icon: 'Delete',
            label: 'Delete all',
            resourceId: 'PlanEntity',
            guard: '',
            showFilter: false,
            component: undefined,
            showInDrawer: true,
            hideActionHeader: false,
            containerWidth: '500px',
            layout: null,
            variant: 'danger',
            parent: null,
            hasHandler: true,
            custom: {},
          },
        ],
      },
    ],
  };
};
